# Generated by Django 4.0.3 on 2022-04-28 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phome',
            new_name='phone',
        ),
    ]
